CREATE TABLE IF NOT EXISTS CREATE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE task (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    postponed BOOLEAN DEFAULT FALSE,
    completed BOOLEAN DEFAULT FALSE
);






